<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="NewLife.Core">
      <HintPath>E:\.nuget\Package\newlife.core\10.10.2024.507\lib\net8.0\NewLife.Core.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceModel.Primitives">
      <HintPath>E:\.nuget\Package\system.servicemodel.primitives\8.0.0\ref\net8.0\System.ServiceModel.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="XCode">
      <HintPath>E:\.nuget\Package\newlife.xcode\11.12.2024.515\lib\net8.0\XCode.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Entity\RuleManagement\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.ServiceModel.NetTcp" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VehicleVedioManage.Utility\VehicleVedioManage.Utility.csproj" />
  </ItemGroup>

</Project>
