name: publish-beta

on:
  push:
    branches: [ master ]
    paths:
        - 'NewLife.Cube/**'
        - 'NewLife.CubeNC/**'
        - 'NewLife.Cube.Metronic/**'
        - 'NewLife.Cube.Metronic8/**'
        - 'NewLife.Cube.LayuiAdmin/**'
  pull_request:
    branches: [ master ]
    paths:
        - 'NewLife.Cube/**'
        - 'NewLife.CubeNC/**'
        - 'NewLife.Cube.Metronic/**'
        - 'NewLife.Cube.Metronic8/**'
        - 'NewLife.Cube.LayuiAdmin/**'
  workflow_dispatch:

jobs:
  build-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotNET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.x
    - name: Get Version
      run: echo "VERSION=$(date '+%Y.%m%d-beta%H%M')" >> $GITHUB_ENV
    - name: Build
      run: |
        dotnet build -c Release --version-suffix ${{ env.VERSION }}
    - name: Pack
      run: |
        dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out NewLife.Cube/NewLife.Cube.csproj
        dotnet pack --no-build --version-suffix ${{ env.VERSION }} -c Release -o out NewLife.CubeNC/NewLife.CubeNC.csproj

    - name: Publish
      run: |
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.pkg.github.com/NewLifeX/index.json --api-key ${{ github.token }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
